#!/bin/bash

# get the directory of the workspace root relative to this source file
WORKSPACE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )/.."

docker build --build-arg USER_ID=$(id -u) -t nook-e-sign .

docker run --rm -it \
	-v $WORKSPACE/:/home/developer/workspace:rw \
	-v nook-e-sign-home:/home/developer:rw \
	nook-e-sign
